# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('char_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('classname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Feats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('item_desc', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=40)),
                ('relevant_ability', models.CharField(choices=[('str', 'str'), ('dex', 'dex'), ('con', 'con'), ('int', 'int'), ('wis', 'wis'), ('cha', 'cha')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Static_Race',
            fields=[
                ('race_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=40)),
                ('password_hash', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('critical', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('range', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Base_Stats',
            fields=[
                ('char_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Character')),
            ],
        ),
        migrations.AddField(
            model_name='weapon',
            name='char_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Character'),
        ),
        migrations.AddField(
            model_name='skills',
            name='char_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Character'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='char_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Character'),
        ),
        migrations.AddField(
            model_name='game',
            name='ran_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
        migrations.AddField(
            model_name='feats',
            name='char_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Character'),
        ),
        migrations.AddField(
            model_name='character',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Game'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Static_Race'),
        ),
        migrations.AddField(
            model_name='character',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
        migrations.AddField(
            model_name='armor',
            name='char_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Character'),
        ),
        migrations.AlterUniqueTogether(
            name='weapon',
            unique_together=set([('char_id', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='skills',
            unique_together=set([('char_id', 'skill_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set([('char_id', 'item_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='feats',
            unique_together=set([('char_id', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='armor',
            unique_together=set([('char_id', 'name')]),
        ),
    ]
