# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='armor_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armor',
            name='armor_check_penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='base_stats',
            name='cha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='base_stats',
            name='con',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='base_stats',
            name='dex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='base_stats',
            name='int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='base_stats',
            name='str',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='base_stats',
            name='wis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skills',
            name='class_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skills',
            name='race_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skills',
            name='ranks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='static_race',
            name='chamod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='static_race',
            name='conmod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='static_race',
            name='dexmod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='static_race',
            name='intmod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='static_race',
            name='strmod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='static_race',
            name='wismod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='damage_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='number_damage_dice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='type_damage_dice',
            field=models.IntegerField(default=0),
        ),
    ]
