# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20171202_0434'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='armor',
            table='armors',
        ),
        migrations.AlterModelTable(
            name='base_stats',
            table='base_stats',
        ),
        migrations.AlterModelTable(
            name='character',
            table='characters',
        ),
        migrations.AlterModelTable(
            name='feats',
            table='feats',
        ),
        migrations.AlterModelTable(
            name='game',
            table='games',
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='inventories',
        ),
        migrations.AlterModelTable(
            name='skills',
            table='skills',
        ),
        migrations.AlterModelTable(
            name='static_race',
            table='static_race',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='weapon',
            table='weapons',
        ),
    ]
