# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20171202_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
