# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20171202_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Game'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(default='Half-Orc', on_delete=django.db.models.deletion.CASCADE, to='website.Static_Race'),
        ),
    ]
