# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20171202_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='game_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Game'),
        ),
    ]
