# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20171202_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='id',
        ),
        migrations.AlterField(
            model_name='armor',
            name='char_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Character'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='char_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Character'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='char_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Character'),
        ),
    ]
