# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20171202_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
