# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20171202_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='armor',
            name='char_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Character'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='char_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Character'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='char_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Character'),
        ),
    ]
