# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20171202_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
